import React, { useState, useEffect } from "react";

import { Loader, Card, FormField } from "../components";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 text-lg font-bold text-indigo-400 uppercase">
      {title}
    </h2>
  );
};

const Home = () => {
  const [loading, setloading] = useState(false);

  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setsearchText] = useState("");

  return (
    <section className="mx-auto max-w-7xl ">
      <div>
        <h1 className="text-xl font-extrabold text-gray-800">
          The Community Showcase
        </h1>
        <p className="mt-2 text-gray-600 text-md max-w-500">
          Browse through a collection of stunning images generated by DALLE-AI
        </p>
      </div>

      <div className="mt-16 ">
        <FormField />
      </div>

      {/*Loader */}
      <div className="mt-10">
        {loading ? (
          <div className="flex items-center justify-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="mb-3 text-xl font-medium text-gray-800">
                Showing results for{" "}
                <span className="text-gray-800">{searchText}</span>
              </h2>
            )}
            <div className="grid gap-3 lg:grid-col-4 sm:grid-cols-3 xs:grid-cols-2 grid-col-1">
              {searchText ? (
                <RenderCards data={[]} title={"No results Found"} />
              ) : (
                <RenderCards data={[]} title={"No posts found"} />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
